on:
  release:
    types: [published]
name: Publish Workflow
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Npm Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Npm Login and Publish
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}