on:
  release:
    types: [published]
name: Publish Workflow
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@conceptho'
      - name: Npm Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Publish
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}